### ISSUE TITLE
Is it drawing field ? 

### ISSUE THREAD

**Issue by munhktamir** [torriem/QtAgOpenGPS#2]
I successfully compiled. But it doesn't visible 2D or 3D map

**Comment by torriem** [comment]
Nothing is drawn until a GPS source is connected. Right now that's only by
sending it udp packets.

**Comment by munhktamir** [comment]
Hello, How can i send udp packets. i want to show field

**Comment by torriem** [comment]
The easiest way is to use Brian Tischler's gps simulator which can send
nmea sentences via Udp (check the qtaog source code for the port number it
defaults too).

On Linux it's fairly easy to read from the serial port and redirect that to
Udp.

The Udp data is expected to be in the same format as the serial data. That
is to say nmea sentences.

**Comment by munhktamir** [comment]
Thank you for your fast response. i will do my best

**Comment by torriem** [comment]
I can give you more details tomorrow. It wouldn't take much code to add
serial port reading to qtaog.

On Dec 12, 2018 23:32, "Munkhtamir" <notifications@github.com> wrote:

Thank you for your fast response. i will do my best

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/torriem/QtAgOpenGPS/issues/2#issuecomment-446857817>,
or mute the thread

**Comment by munhktamir** [comment]
Thank you. i will waiting for you

**Comment by munhktamir** [comment]
@torriem Hello. Did you add serial port part to QtAOG. i tried to send packet via UDP. But it didn't appear.

**Comment by torriem** [comment]
No like I said it's easy to do but I won't have time to work on it until
January.

Did you try the simulator Brian posted?

**Comment by munhktamir** [comment]
yes I built the GPSAgSim/**AgSim_UDP** then I configured the UDP client and server ip address with port. QtAOG didn't get data from **AgSim_UDP**

**Comment by dlipicar** [comment]
Make sure you set port 9999 with your current IP in the simulator, enable GGA & VTG meesages, and press "Connect". I've just tried it on Windows and QtAgOpenGPS (nealholl's fork) started rendering the field without any issue.

**Comment by munhktamir** [comment]
@dlipicar thank you for explain it. i did it successfully. Is there any simulator in Linux ?

**Comment by torriem** [comment]
You can try to run the simulator under mono on Linux. Or maybe it would
require wine. I know that AOG itself runs quite well under wine. On Linux.

On Dec 15, 2018 20:50, "Munkhtamir" <notifications@github.com> wrote:

@dlipicar <https://github.com/dlipicar> thank you for explain it. i did it
successfully. Is there any simulator in Linux ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/torriem/QtAgOpenGPS/issues/2#issuecomment-447615732>,
or mute the thread

**Comment by munhktamir** [comment]
@torriem Do you know about version of Qt. You advised Qt version that must be  5.8 or higher. Is it possible to decrease Qt version to 5.6.2.

**Comment by torriem** [comment]
On 2018-12-16 12:33 a.m., Munkhtamir wrote:
> @torriem Do you know about version of Qt. You advised Qt version that must be  5.8 or higher. Is it possible to decrease Qt version to 5.6.2.

I am not sure. All I know is I was using Qt 5.9.4 when I last worked on
QtAOG.  Give it a try and see what happens.

**Comment by munhktamir** [comment]
AOG was developed on Windows by using C# with OpenGL Desktop API. But i want to test the QtAOG on Embedded development board. That code written and used OpenGL Desktop API. It means i have to convert to the OpenGL ES right ?

**Comment by torriem** [comment]
On 2018-12-16 9:04 a.m., Munkhtamir wrote:
> AOG was developed on Windows by using C# with OpenGL Desktop API. But i want to test the QtAOG on Embedded development board. That code written and used OpenGL Desktop API. It means i have to convert to the OpenGL ES right ? 

Currently all the OpenGL code in QtAOG is OpenGL ES.  Additional OpenGL
code ported from C# AOG is not OpenGL ES and would have to be converted
to use shaders and buffers.  The shaders are not complicated; you can
see the shaders I use in QtAOG.

**Comment by munhktamir** [comment]
i used Buildroot for make the Linux image. There has several api of OpenGL ES version 1,2, and 3. Also, version of Qt is 5.9.2. But several opengl functions cannot found from API. you know, for example glMatrixMode(.....)

**Comment by munhktamir** [comment]
Hello, i uploaded the error. 
![untitled](https://user-images.githubusercontent.com/11732020/50063717-02f70500-01f1-11e9-9837-fb1306eae609.png)

**Comment by torriem** [comment]
Oh good catch.  If you notice ccamera.cpp defines two functions with the
same name; the old OpenGL 2.1 version and the newer OpenGL ES one.  The
older version of the method is no longer used by any other code now, so
it can be summarily deleted.  I removed that from my code and it builds,
so I've pushed it up to github. Try pulling the latest revision and see
if it builds for you.

**Comment by munhktamir** [comment]
Hello, @torriem. I encountered another problem in embedded. when I execute application over the embedded board, it will be aborted and gives like 'EGLFS: OpenGL windows cannot be mixed with others.' Then I found the following post.  
![image](https://user-images.githubusercontent.com/11732020/50096021-1f7b5780-025a-11e9-8572-3746d3387998.png)
What are you thinking about it? Should we change UI integration?

**Comment by torriem** [comment]
On 12/17/2018 08:17 AM, Munkhtamir wrote:
> Hello, @torriem. I encountered another problem in embedded. when I execute application over the embedded board, it will be aborted and gives like 'EGLFS: OpenGL windows cannot be mixed with others.' Then I found the following post.  
> ![image](https://user-images.githubusercontent.com/11732020/50096021-1f7b5780-025a-11e9-8572-3746d3387998.png)
> What are you thinking about it? Should we change UI integration?

In QtAOG all visible OpenGL drawing is done using the same context and
window of the main QtQuick window.  So that won't be a problem.  The
only thing I can think of is that perhaps it doesn't like the off-screen
OpenGL context that the look-ahead code is using.  You'll have to verify
that that is the problem by commenting out any code that sets up the
off-screen context and any opengl code that uses that.  If the problem
goes away, then we know that was it.  Unfortunately I have no idea how
to solve it if that's the problem.  You may have to consult with Qt's
online forums about using off-screen OpenGL contexts with EGLFS.

**Comment by torriem** [comment]
So I did a bit of testing today and I get the same message as you when I
try the EGLFS target.  All of the examples work that ship with Qt,
including ones that do their own OpenGL drawing in a QtQuick item,
similar to what I'm doing. Still think it could be the offscreen opengl
stuff that's causing it, but I commented it all out and I still see this
message. It could be that I'm using QtQuick in a QQuickView widget,
embedded in a normal QMainWindow with a menu bar.  That might be part of
the problem.  Eventually I intend for all parts of the UI to be in
QtQuick, so I won't use any of the traditional Qt widget set.  Then
maybe I would just derive FormGPS from QQuickWindow.  Anyway I will look
into this more when I can, but it will be quite a while before I have
time to really dive into it.  In the meantime if you solve the problem,
let me know and I'll be happy to merge any fixes.

**Comment by munhktamir** [comment]
Yes. I am sure with you. there has several platform selections for displaying GUI in target board. In fact, i executed QtAOG by using linuxfb. It displayed poorly widgets without any error. So i thought, It might be integrating between Widget and QML that gives error. I am trying to fix it. I will inform to you when i successful.

**Comment by munhktamir** [comment]
Hello, Dear Torriem. How are you? I was really busy to graduate my master course. 
Now, I am available to develop QtAgOpenGPS. A few days, I spent time to prepare my hardware. Today, I successfully modified Qt5.9.8 to i.MX6Q microprocessor. I have compiled application but I occurred some problem when i execute. see the picture.
![64484640_610640166090336_6532845681864867840_n](https://user-images.githubusercontent.com/11732020/59484619-7b433800-8ead-11e9-87df-75b6b42da954.png)

How can i solve this? did you faced with this error ?

**Comment by ConarDanial** [comment]
> @dlipicar thank you for explain it. i did it successfully. Is there any simulator in Linux ?

Hi munhktamir,

I am trying to get QtAgOpenGPS to render fields but I am not succeeding...I am aware that there isnt a serial port implemented in the code, how did you mange to get QtAgOpen to render fields on Linux? My current attempt was to run AgOpenGPS on wine so that the GPS simulator sends NMEA UDP packets to port 9999, but QtAgOpenGPS did not pick up anything...any suggestions? thank you

**Comment by munhktamir** [comment]
Hi Conar,

Do you have a GPS simulator made by Brian Tee?

If you have, Could you share it with me?

I tried to render it on embedded dev board but we have to fix something such as rendering QWidget class with QML window.

I didn't succeed yet. I think that it won't take a long time to implement.

**Comment by torriem** [comment]
OpenGL drawing should work on all Qt platforms now, and simulator built in now that code has been updated to track with the latest AOG github commit as of this date.
